version: '3.7'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgres14-devise-example'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    container_name: 'devise-example'
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/devise-example
      - gems:/gems

volumes:
  postgres:
  gems: